// deno-lint-ignore-file

// This file is automatically generated by deno_bindgen.
// Do not edit this file directly.

let symbols: any;

export function load(path: string) {
  const { dlopen } = Deno;

  const { symbols: symbols_ } = dlopen(path, {
    midi_init: {
      parameters: [],
      result: "void",
      nonblocking: false,
    },
    midi_devices: {
      parameters: [],
      result: "pointer",
      nonblocking: false,
    },
    midi_send_message: {
      parameters: ["i32", "u8", "u8", "u8", "u8"],
      result: "void",
      nonblocking: false,
    },
  });

  symbols = symbols_;
}

export function midi_init(): void {
  return symbols.midi_init();
}

export function midi_devices(): Deno.PointerObject | null {
  return symbols.midi_devices();
}

export function midi_send_message(
  device_id: number,
  arg0: number,
  arg1: number,
  arg2: number,
  arg3: number,
): void {
  return symbols.midi_send_message(device_id, arg0, arg1, arg2, arg3);
}
